[project]
name = "sd-scripts-docker"
version = "0.0.0"
requires-python = "==3.10.*"

# Originally copied from kohya-ss/sd-scripts
# https://github.com/kohya-ss/sd-scripts/blob/6721028c79ee85a78b3a06dfd8954dae310a1cce/requirements.txt
dependencies = [
  "accelerate==1.6.0",
  "transformers==5.10.1",
  "diffusers[torch]==0.38.0",
  "ftfy==6.3.1",
  "opencv-python==4.10.0.84",
  "einops==0.7.0",
  "bitsandbytes",
  "lion-pytorch==0.2.3",
  "schedulefree==1.4",
  "pytorch-optimizer==3.10.0",
  "prodigy-plus-schedule-free==1.9.2",
  "prodigyopt==1.1.2",
  "tensorboard",
  "safetensors==0.8.0rc0",
  "toml==0.10.2",
  "voluptuous==0.15.2",
  "huggingface-hub==1.14.0",
  # for Image utils
  "imagesize==1.4.1",
  "numpy",
  # for BLIP captioning
  "requests==2.33.0",
  "timm==0.6.12",
  "fairscale==0.4.13",
  # for WD14 captioning (onnx)
  "onnx==1.22.0",
  "onnxruntime-gpu==1.23.2",
  # open clip for SDXL
  "open-clip-torch==2.26.1",
  # For logging
  "rich==14.1.0",
  # for T5XXL tokenizer (SD3/FLUX)
  "sentencepiece==0.2.1",
  # PyTorch
  "torch==2.13.0+cu130",
  "torchvision==0.28.0+cu130",
  "xformers==0.0.35",
  # Additional bundle
  # https://github.com/KohakuBlueleaf/LyCORIS
  "lycoris-lora==3.1.1.post1",
]

[tool.uv]
package = false
exclude-newer = "P7D"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
xformers = { index = "pytorch-cu130" }

[dependency-groups]
dev = [
  "pytest>=9.1.1",
]
